name: CI-CD Docker Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: webapp-ci-cd
  IMAGE_TAG: 1.0.1

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push
        run: |
         

  deploy:
    needs: ci
    runs-on: runner-lab
    steps:
      - name: Deploy Container
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker stop ci-app || true
          docker rm ci-app || true
          docker run -d -p 80:80 --name ci-app ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
