name: Pipeline CI-CD Forty

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Étape 1 : Vérification du code
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Vérification des fichiers
        run: ls -la

  # Étape 2 : Scan de sécurité (Le fameux Bonus Trivy)
  scan-trivy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs' # On scanne le système de fichiers
          scan-ref: '.'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1' # Le pipeline s'arrête s'il y a un danger

  # Étape 3 : Déploiement (Simulation)
  deploy:
    runs-on: ubuntu-latest
    needs: scan-trivy
    steps:
      - name: Simulation Déploiement
        run: |
          echo "Le scan est OK. Déploiement en cours..."
          echo "Application déployée avec succès !"
